name: Package homebrew

on:
  push:


jobs:
  package-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Create formula
        run: |
          mkdir -p Formula
          wget --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.zip.sha256
          SHA256ZIP=$(cat axelard-darwin-amd64-v0.32.2.zip.sha256)
           wget --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.sha256
          SHA256=$(cat axelard-darwin-amd64-v0.32.2.sha256)         
          echo "class Axelard < Formula
            desc "Axelard binary for darwin"
            homepage "https://axelar.network"
            url url "https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.zip"
            version "0.32.2"
            sha256 "$SHA256ZIP"

            resource "axelard" do
              url "https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2"
              sha256 "$SHA256"
            end

            def install
              resource("axelard").stage do
                bin.install "axelard"
              end
            end" > axelard.rb
          cat axelard.rb
          mv axelard.rb Formula
          rm -fr axelard-darwin-amd64-v0.32.2.zip.sha256
          rm -fr axelard-darwin-amd64-v0.32.2.sha256
  
      - name: Commit files
        run: |
          git config --local user.email "kalid@axelar.network"
          git config --local user.name "kalid"
          git add --all
          git diff-index --quiet HEAD -- ||  git commit -m "create formula"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Register the formula in homebrew
        run: |
          brew tap kalidux/axelard https://github.com/kalidux/homebrew-axelard.git
          
      - name: install the binary
        run: |
          brew doctor 
          brew config 
          brew install axelard
