name: Package homebrew

on:
  push:


jobs:
  package-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Create formula
        run: |
          wget --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.zip.sha256
          SHA256=$(cat axelard-darwin-amd64-v0.32.2.zip.sha256)
          echo "class Heft < Formula
            desc "axelard binary for darwin"
            homepage "https://axelar.network"
            url "https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.zip"
            version "0.32.2"
            sha256 "$SHA256"
            def install
              bin.install "heft"
            end
          end" > axelard.rb
          cat axelard.rb
