name: Package homebrew

on:
  push:


jobs:
  package-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Create formula
        run: |
          mkdir Formula
          wget --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.zip.sha256
          SHA256=$(cat axelard-darwin-amd64-v0.32.2.zip.sha256)
          echo "class Heft < Formula
            desc "axelard binary for darwin"
            homepage "https://axelar.network"
            url "https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.zip"
            version "0.32.2"
            sha256 "$SHA256"
            def install
              bin.install "heft"
            end
          end" > axelard.rb
          mv axelard.rb Formula
  
      - name: Commit files
        run: |
          git config --local user.email "kalid@axelar.network"
          git config --local user.name "kalid"
          git add --all
          git commit -m "create formula"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
